/**
 * EAM (Enterprise Asset Management) Operations Seed Data
 *
 * Seeds work orders, spare parts, and linear assets
 * to populate EAM-specific tables for realistic demo/test data.
 */

import type {
  SeedWorkOrder,
  SeedSparePart,
  SeedLinearAsset,
} from './types';

// ============================================================================
// Work Orders
// ============================================================================

export const WORK_ORDERS: SeedWorkOrder[] = [
  {
    workOrderNumber: 'WO-2025-001',
    assetDisplayName: 'Main HVAC System',
    workType: 'PREVENTIVE',
    priority: 'HIGH',
    status: 'COMPLETED',
    title: 'Q1 HVAC Preventive Maintenance',
    description: 'Quarterly preventive maintenance including filter replacement, coil cleaning, refrigerant check, and belt inspection',
    estimatedDurationHours: 4,
    assignedToEmail: 'technician@example.com',
    facilityCode: 'HQ',
    scheduledDateOffsetDays: -30,
  },
  {
    workOrderNumber: 'WO-2025-002',
    assetDisplayName: 'Backup Generator A',
    workType: 'PREVENTIVE',
    priority: 'CRITICAL',
    status: 'COMPLETED',
    title: 'Monthly Generator Load Test',
    description: 'Monthly full-load test of backup generator A including fuel system check, coolant levels, and transfer switch verification',
    estimatedDurationHours: 2,
    assignedToEmail: 'technician@example.com',
    facilityCode: 'DC1',
    scheduledDateOffsetDays: -15,
  },
  {
    workOrderNumber: 'WO-2025-003',
    assetDisplayName: 'Elevator B - HQ',
    workType: 'CORRECTIVE',
    priority: 'HIGH',
    status: 'IN_PROGRESS',
    title: 'Elevator Door Sensor Replacement',
    description: 'Replace faulty door proximity sensor on elevator B. Intermittent door closure failures reported by building occupants.',
    estimatedDurationHours: 3,
    assignedToEmail: 'technician@example.com',
    facilityCode: 'HQ',
    scheduledDateOffsetDays: 0,
  },
  {
    workOrderNumber: 'WO-2025-004',
    assetDisplayName: 'UPS System - DC1',
    workType: 'PREVENTIVE',
    priority: 'CRITICAL',
    status: 'OPEN',
    title: 'Annual UPS Battery Replacement',
    description: 'Replace battery modules in UPS system. Batteries approaching end of rated life per manufacturer specifications.',
    estimatedDurationHours: 8,
    assignedToEmail: 'technician@example.com',
    facilityCode: 'DC1',
    scheduledDateOffsetDays: 7,
  },
  {
    workOrderNumber: 'WO-2025-005',
    assetDisplayName: 'Fire Suppression System',
    workType: 'INSPECTION',
    priority: 'HIGH',
    status: 'OPEN',
    title: 'Semi-Annual Fire Suppression Inspection',
    description: 'Inspect FM-200 agent levels, nozzle alignment, detection sensors, and control panel. Required by fire marshal.',
    estimatedDurationHours: 3,
    facilityCode: 'DC1',
    scheduledDateOffsetDays: 14,
  },
  {
    workOrderNumber: 'WO-2025-006',
    assetDisplayName: 'CRAC Unit - DC1',
    workType: 'CORRECTIVE',
    priority: 'CRITICAL',
    status: 'IN_PROGRESS',
    title: 'CRAC Unit Compressor Repair',
    description: 'Compressor showing elevated temperature readings. Possible refrigerant leak detected. Immediate investigation required.',
    estimatedDurationHours: 6,
    assignedToEmail: 'technician@example.com',
    facilityCode: 'DC1',
    scheduledDateOffsetDays: -1,
  },
  {
    workOrderNumber: 'WO-2025-007',
    assetDisplayName: 'Warehouse Forklift 1',
    workType: 'PREVENTIVE',
    priority: 'MEDIUM',
    status: 'OPEN',
    title: 'Weekly Forklift Safety Inspection',
    description: 'Perform weekly OSHA-required safety inspection: brakes, steering, tires, lights, horn, forks, hydraulics',
    estimatedDurationHours: 0.5,
    facilityCode: 'WH-EAST',
    scheduledDateOffsetDays: 1,
  },
  {
    workOrderNumber: 'WO-2025-008',
    assetDisplayName: 'Security Camera System',
    workType: 'CORRECTIVE',
    priority: 'MEDIUM',
    status: 'OPEN',
    title: 'Camera Lens Cleaning and Recalibration',
    description: 'Multiple cameras showing degraded image quality. Clean lenses and recalibrate PTZ motors on 8 exterior cameras.',
    estimatedDurationHours: 4,
    facilityCode: 'HQ',
    scheduledDateOffsetDays: 5,
  },
  {
    workOrderNumber: 'WO-2025-009',
    assetDisplayName: 'Access Control System',
    workType: 'PREVENTIVE',
    priority: 'HIGH',
    status: 'SCHEDULED',
    title: 'Annual Access Control System Audit',
    description: 'Annual audit of all card readers, door locks, and access control firmware. Update firmware, replace batteries, verify log integrity.',
    estimatedDurationHours: 8,
    assignedToEmail: 'technician@example.com',
    facilityCode: 'HQ',
    scheduledDateOffsetDays: 21,
  },
  {
    workOrderNumber: 'WO-2025-010',
    assetDisplayName: 'Backup Generator B',
    workType: 'EMERGENCY',
    priority: 'CRITICAL',
    status: 'COMPLETED',
    title: 'Emergency Fuel Leak Repair',
    description: 'Fuel leak detected during routine inspection. Emergency repair of fuel line fitting and gasket replacement.',
    estimatedDurationHours: 4,
    assignedToEmail: 'technician@example.com',
    facilityCode: 'DC1',
    scheduledDateOffsetDays: -45,
  },
];

// ============================================================================
// Spare Parts
// ============================================================================

export const SPARE_PARTS: SeedSparePart[] = [
  {
    partNumber: 'SP-HVAC-FILT-001',
    partName: 'HVAC Air Filter 20x25x4',
    description: 'MERV 13 pleated air filter for Carrier WeatherExpert 50XC units',
    manufacturer: 'Carrier',
    category: 'HVAC',
    quantityOnHand: 24,
    reorderPoint: 8,
    reorderQuantity: 24,
    unitCost: 45.00,
    storageLocation: 'WH-EAST / Aisle 3 / Shelf B',
    isCritical: false,
    abcClassification: 'B',
  },
  {
    partNumber: 'SP-HVAC-BELT-002',
    partName: 'HVAC Drive Belt A68',
    description: 'V-belt for Carrier blower motor, size A68',
    manufacturer: 'Gates',
    category: 'HVAC',
    quantityOnHand: 6,
    reorderPoint: 2,
    reorderQuantity: 6,
    unitCost: 28.50,
    storageLocation: 'WH-EAST / Aisle 3 / Shelf B',
    isCritical: false,
    abcClassification: 'C',
  },
  {
    partNumber: 'SP-GEN-OIL-003',
    partName: 'Generator Oil Filter',
    description: 'Oil filter for Caterpillar C18 ACERT diesel generator',
    manufacturer: 'Caterpillar',
    category: 'ELECTRICAL',
    quantityOnHand: 8,
    reorderPoint: 4,
    reorderQuantity: 8,
    unitCost: 65.00,
    storageLocation: 'WH-EAST / Aisle 5 / Shelf A',
    isCritical: true,
    abcClassification: 'A',
  },
  {
    partNumber: 'SP-GEN-FUEL-004',
    partName: 'Generator Fuel Filter',
    description: 'Primary fuel filter for Caterpillar C18 ACERT',
    manufacturer: 'Caterpillar',
    category: 'ELECTRICAL',
    quantityOnHand: 6,
    reorderPoint: 2,
    reorderQuantity: 6,
    unitCost: 85.00,
    storageLocation: 'WH-EAST / Aisle 5 / Shelf A',
    isCritical: true,
    abcClassification: 'A',
  },
  {
    partNumber: 'SP-UPS-BAT-005',
    partName: 'UPS Battery Module 12V 100Ah',
    description: 'Replacement battery module for Eaton 93PM UPS system',
    manufacturer: 'Eaton',
    category: 'ELECTRICAL',
    quantityOnHand: 4,
    reorderPoint: 2,
    reorderQuantity: 8,
    unitCost: 450.00,
    storageLocation: 'WH-EAST / Aisle 5 / Shelf C',
    isCritical: true,
    abcClassification: 'A',
  },
  {
    partNumber: 'SP-ELEV-SENS-006',
    partName: 'Elevator Door Proximity Sensor',
    description: 'Infrared door proximity sensor for Otis Gen2 Premier elevators',
    manufacturer: 'Otis',
    category: 'ELEVATOR',
    quantityOnHand: 3,
    reorderPoint: 2,
    reorderQuantity: 4,
    unitCost: 320.00,
    storageLocation: 'WH-EAST / Aisle 7 / Shelf A',
    isCritical: true,
    abcClassification: 'A',
  },
  {
    partNumber: 'SP-CRAC-REF-007',
    partName: 'CRAC Refrigerant R-410A (25lb)',
    description: 'R-410A refrigerant cylinder for Liebert DS units',
    manufacturer: 'Chemours',
    category: 'HVAC',
    quantityOnHand: 3,
    reorderPoint: 1,
    reorderQuantity: 3,
    unitCost: 280.00,
    storageLocation: 'WH-EAST / Aisle 3 / Shelf D (Hazmat)',
    isCritical: true,
    abcClassification: 'A',
  },
  {
    partNumber: 'SP-CAM-LENS-008',
    partName: 'Security Camera Lens Assembly',
    description: 'Replacement varifocal lens for Axis P3245-V cameras',
    manufacturer: 'Axis',
    category: 'SECURITY',
    quantityOnHand: 5,
    reorderPoint: 2,
    reorderQuantity: 5,
    unitCost: 175.00,
    storageLocation: 'WH-EAST / Aisle 8 / Shelf B',
    isCritical: false,
    abcClassification: 'B',
  },
  {
    partNumber: 'SP-ACC-BAT-009',
    partName: 'Card Reader Backup Battery CR123A',
    description: 'Lithium battery for HID card reader backup power',
    manufacturer: 'Panasonic',
    category: 'SECURITY',
    quantityOnHand: 50,
    reorderPoint: 20,
    reorderQuantity: 50,
    unitCost: 3.50,
    storageLocation: 'WH-EAST / Aisle 8 / Shelf C',
    isCritical: false,
    abcClassification: 'C',
  },
  {
    partNumber: 'SP-FORK-TIRE-010',
    partName: 'Forklift Solid Tire 18x7-8',
    description: 'Solid rubber tire for Toyota 8FBMT25 electric forklift',
    manufacturer: 'Continental',
    category: 'TRANSPORTATION',
    quantityOnHand: 4,
    reorderPoint: 2,
    reorderQuantity: 4,
    unitCost: 195.00,
    storageLocation: 'WH-EAST / Aisle 10 / Floor',
    isCritical: false,
    abcClassification: 'B',
  },
  {
    partNumber: 'SP-FIRE-AGENT-011',
    partName: 'FM-200 Agent Cylinder (100lb)',
    description: 'FM-200 clean agent cylinder for Kidde ECS fire suppression',
    manufacturer: 'Kidde',
    category: 'FIRE_SAFETY',
    quantityOnHand: 1,
    reorderPoint: 1,
    reorderQuantity: 2,
    unitCost: 1250.00,
    storageLocation: 'WH-EAST / Aisle 6 / Shelf A (Hazmat)',
    isCritical: true,
    abcClassification: 'A',
  },
  {
    partNumber: 'SP-CRAC-FILT-012',
    partName: 'CRAC Unit Air Filter',
    description: 'HEPA filter for Liebert DS 105kW CRAC unit',
    manufacturer: 'Liebert',
    category: 'HVAC',
    quantityOnHand: 6,
    reorderPoint: 2,
    reorderQuantity: 6,
    unitCost: 120.00,
    storageLocation: 'WH-EAST / Aisle 3 / Shelf C',
    isCritical: false,
    abcClassification: 'B',
  },
];

// ============================================================================
// Linear Assets
// ============================================================================

export const LINEAR_ASSETS: SeedLinearAsset[] = [
  {
    assetDisplayName: 'Main HVAC System',
    startLocation: 'HQ Building A - Mechanical Room',
    endLocation: 'HQ Building A - Roof Penthouse',
    totalLength: 450.0,
    linearUnit: 'METERS',
    routeType: 'DUCTWORK',
    routeDescription: 'Primary HVAC supply ductwork from mechanical room to roof penthouse via 4 floors',
    overallCondition: 'GOOD',
    segments: [
      { sequenceNumber: 1, startMarker: 'MR-01', endMarker: 'FL1-01', segmentLength: 85.0, conditionRating: 'GOOD', material: 'GALVANIZED_STEEL', segmentDescription: 'Basement mechanical room to 1st floor plenum' },
      { sequenceNumber: 2, startMarker: 'FL1-01', endMarker: 'FL2-01', segmentLength: 95.0, conditionRating: 'GOOD', material: 'GALVANIZED_STEEL', segmentDescription: '1st floor to 2nd floor vertical riser' },
      { sequenceNumber: 3, startMarker: 'FL2-01', endMarker: 'FL3-01', segmentLength: 95.0, conditionRating: 'FAIR', material: 'GALVANIZED_STEEL', segmentDescription: '2nd floor to 3rd floor - minor corrosion noted' },
      { sequenceNumber: 4, startMarker: 'FL3-01', endMarker: 'FL4-01', segmentLength: 95.0, conditionRating: 'GOOD', material: 'GALVANIZED_STEEL', segmentDescription: '3rd floor to 4th floor vertical riser' },
      { sequenceNumber: 5, startMarker: 'FL4-01', endMarker: 'ROOF-01', segmentLength: 80.0, conditionRating: 'EXCELLENT', material: 'GALVANIZED_STEEL', segmentDescription: '4th floor to roof penthouse - recently replaced' },
    ],
  },
  {
    assetDisplayName: 'Fire Suppression System',
    startLocation: 'DC1 - Agent Storage Room',
    endLocation: 'DC1 - Server Hall C',
    totalLength: 120.0,
    linearUnit: 'METERS',
    routeType: 'PIPING',
    routeDescription: 'FM-200 distribution piping from agent storage to server hall nozzles',
    overallCondition: 'EXCELLENT',
    segments: [
      { sequenceNumber: 1, startMarker: 'ASR-01', endMarker: 'MH-01', segmentLength: 25.0, conditionRating: 'EXCELLENT', material: 'STAINLESS_STEEL', segmentDescription: 'Agent storage room to main header' },
      { sequenceNumber: 2, startMarker: 'MH-01', endMarker: 'SHA-01', segmentLength: 35.0, conditionRating: 'EXCELLENT', material: 'STAINLESS_STEEL', segmentDescription: 'Main header to Server Hall A distribution' },
      { sequenceNumber: 3, startMarker: 'SHA-01', endMarker: 'SHB-01', segmentLength: 30.0, conditionRating: 'EXCELLENT', material: 'STAINLESS_STEEL', segmentDescription: 'Server Hall A to Server Hall B distribution' },
      { sequenceNumber: 4, startMarker: 'SHB-01', endMarker: 'SHC-01', segmentLength: 30.0, conditionRating: 'EXCELLENT', material: 'STAINLESS_STEEL', segmentDescription: 'Server Hall B to Server Hall C distribution' },
    ],
  },
  {
    assetDisplayName: 'Security Camera System',
    startLocation: 'HQ - Main Server Room',
    endLocation: 'HQ - Parking Structure P3',
    totalLength: 850.0,
    linearUnit: 'METERS',
    routeType: 'CABLING',
    routeDescription: 'Cat6A ethernet backbone for IP camera network from server room to all camera locations',
    overallCondition: 'GOOD',
    segments: [
      { sequenceNumber: 1, startMarker: 'SVR-01', endMarker: 'IDF-1', segmentLength: 150.0, conditionRating: 'EXCELLENT', material: 'CAT6A_COPPER', segmentDescription: 'Server room to IDF 1st floor' },
      { sequenceNumber: 2, startMarker: 'IDF-1', endMarker: 'IDF-2', segmentLength: 120.0, conditionRating: 'GOOD', material: 'CAT6A_COPPER', segmentDescription: 'IDF 1st floor to IDF 2nd floor' },
      { sequenceNumber: 3, startMarker: 'IDF-2', endMarker: 'IDF-EXT', segmentLength: 200.0, conditionRating: 'GOOD', material: 'CAT6A_COPPER', segmentDescription: 'IDF 2nd floor to exterior junction box' },
      { sequenceNumber: 4, startMarker: 'IDF-EXT', endMarker: 'PKG-P1', segmentLength: 180.0, conditionRating: 'FAIR', material: 'CAT6A_COPPER', segmentDescription: 'Exterior junction to Parking Level P1 - weathering observed' },
      { sequenceNumber: 5, startMarker: 'PKG-P1', endMarker: 'PKG-P2', segmentLength: 100.0, conditionRating: 'GOOD', material: 'CAT6A_COPPER', segmentDescription: 'Parking P1 to P2' },
      { sequenceNumber: 6, startMarker: 'PKG-P2', endMarker: 'PKG-P3', segmentLength: 100.0, conditionRating: 'GOOD', material: 'CAT6A_COPPER', segmentDescription: 'Parking P2 to P3' },
    ],
  },
];
