export const STATIC_ROUTES: { path: string; name: string }[] = [
  { path: '/login', name: 'Login' },
  { path: '/', name: 'Dashboard' },
  { path: '/assets', name: 'All Assets' },
  { path: '/assets/hardware', name: 'Hardware Assets' },
  { path: '/assets/software', name: 'Software Assets' },
  { path: '/assets/enterprise', name: 'Enterprise Assets' },
  { path: '/assets/new', name: 'Create Asset' },

  { path: '/stockrooms', name: 'Stockrooms' },
  { path: '/contracts', name: 'Contracts' },
  { path: '/licenses', name: 'License Workbench' },
  { path: '/service-catalog', name: 'Service Catalog' },

  { path: '/procurement', name: 'Procurement Overview' },
  { path: '/procurement/purchase-orders', name: 'Purchase Orders' },
  { path: '/procurement/purchase-orders/new', name: 'Create Purchase Order' },
  { path: '/procurement/receiving', name: 'Receiving' },

  { path: '/ham/transfers', name: 'HAM Transfers' },
  { path: '/ham/loaners', name: 'HAM Loaners' },
  { path: '/ham/audit-scans', name: 'HAM Audit Scans' },
  { path: '/ham/disposal', name: 'HAM Disposal' },

  { path: '/eam/work-orders', name: 'EAM Work Orders' },
  { path: '/eam/maintenance-plans', name: 'EAM Maintenance Plans' },
  { path: '/eam/linear-assets', name: 'EAM Linear Assets' },
  { path: '/eam/parts-inventory', name: 'EAM Parts Inventory' },

  { path: '/reports', name: 'Reports' },
  { path: '/reports/asset-summary', name: 'Asset Summary Report' },
  { path: '/reports/asset-aging', name: 'Asset Aging Report' },
  { path: '/reports/assets-by-location', name: 'Assets by Location' },
  { path: '/reports/assets-by-department', name: 'Assets by Department' },
  { path: '/reports/cost-center-utilization', name: 'Cost Center Utilization' },
  { path: '/reports/procurement-spending', name: 'Procurement Spending' },
  { path: '/reports/work-order-summary', name: 'Work Order Summary' },
  { path: '/reports/maintenance-compliance', name: 'Maintenance Compliance' },

  { path: '/admin', name: 'Admin Redirect' },
  { path: '/admin/locations', name: 'Admin Locations' },
  { path: '/admin/storage', name: 'Admin Storage' },
  { path: '/admin/departments', name: 'Admin Departments' },
  { path: '/admin/departments/new', name: 'Create Department' },
  { path: '/admin/cost-centers', name: 'Admin Cost Centers' },
  { path: '/admin/cost-centers/new', name: 'Create Cost Center' },
  { path: '/admin/vendors', name: 'Admin Vendors' },
  { path: '/admin/vendors/new', name: 'Create Vendor' },
  { path: '/admin/manufacturers', name: 'Admin Manufacturers' },
  { path: '/admin/manufacturers/new', name: 'Create Manufacturer' },
  { path: '/admin/products', name: 'Admin Products' },
  { path: '/admin/products/new', name: 'Create Product' },
  { path: '/admin/users', name: 'Admin Users' },

  { path: '/settings', name: 'Settings' },
  { path: '/notifications/preferences', name: 'Notification Preferences' },
];
