"use strict";
/**
 * Event types for event-driven architecture
 *
 * This module defines all domain events published by the Asset Management System.
 * Events follow a consistent structure with typed payloads for type safety.
 *
 * Requirements: 9.1, 9.2 - Event-Driven Architecture
 */
Object.defineProperty(exports, "__esModule", { value: true });
exports.EVENT_CATEGORIES = exports.ALL_EVENT_TYPES = void 0;
exports.getEventCategory = getEventCategory;
exports.isValidEventType = isValidEventType;
exports.createEvent = createEvent;
exports.extractEventMetadata = extractEventMetadata;
/**
 * All valid event types as an array for validation
 */
exports.ALL_EVENT_TYPES = [
    // Asset events
    'ASSET_CREATED', 'ASSET_UPDATED', 'ASSET_DELETED', 'ASSET_STATE_CHANGED',
    'ASSET_ASSIGNED', 'ASSET_DEPLOYED', 'ASSET_RETIRED', 'ASSET_REASSIGNED',
    // SAM events
    'RECONCILIATION_COMPLETED', 'RECONCILIATION_RUN_COMPLETED',
    'RECLAMATION_INITIATED', 'RECLAMATION_STATUS_CHANGED', 'RECLAMATION_CANDIDATE_IDENTIFIED',
    'RECLAMATION_IDENTIFICATION_COMPLETED', 'RECLAMATION_WORKFLOW_INITIATED',
    'RECLAMATION_USER_NOTIFICATION', 'RECLAMATION_MANAGER_NOTIFICATION',
    'RECLAMATION_APPROVED', 'RECLAMATION_REJECTED', 'RECLAMATION_COMPLETED', 'RECLAMATION_CANCELLED',
    'SHADOW_IT_DETECTED', 'SHADOW_IT_ALERT_CREATED', 'SHADOW_IT_ANALYSIS_COMPLETED',
    'SHADOW_IT_STATUS_CHANGED', 'SHADOW_IT_ALERT_ACKNOWLEDGED', 'SHADOW_IT_ALERT_RESOLVED', 'SHADOW_IT_ALERT_IGNORED',
    'SAAS_SUBSCRIPTION_CREATED', 'SAAS_SUBSCRIPTION_UPDATED', 'SAAS_USAGE_SYNCED',
    'SAAS_OPTIMIZATION_OPPORTUNITIES_FOUND', 'SAAS_RENEWAL_NOTIFICATION_CREATED',
    'SAAS_RENEWAL_NOTIFICATION_SENT', 'SAAS_RENEWAL_NOTIFICATION_ACKNOWLEDGED', 'SAAS_SUBSCRIPTION_DELETED',
    'PUBLISHER_CALCULATION_COMPLETED', 'COMPLIANCE_REPORT_GENERATED', 'COMPLIANCE_REPORT_EXPORTED',
    // HAM events
    'TRANSFER_ORDER_CREATED', 'TRANSFER_ORDER_COMPLETED', 'TRANSFER_ORDER_APPROVED',
    'TRANSFER_ORDER_REJECTED', 'TRANSFER_ORDER_SHIPPED', 'TRANSFER_ORDER_CANCELLED', 'TRANSFER_LINE_RECEIVED',
    'STOCK_LEVEL_ALERT', 'INVENTORY_CREATED', 'INVENTORY_UPDATED', 'INVENTORY_ADJUSTED',
    'INVENTORY_RESERVED', 'INVENTORY_RESERVATION_RELEASED', 'REPLENISHMENT_ALERT',
    'LOANER_CHECKOUT', 'LOANER_RETURNED', 'LOANER_OVERDUE',
    'LOANER_CHECKED_OUT', 'LOANER_OVERDUE_NOTIFICATION', 'LOANER_DUE_DATE_EXTENDED',
    'AUDIT_COMPLETED', 'AUDIT_SCAN_RECORDED', 'DISPOSAL_COMPLETED',
    'DISPOSAL_WORKFLOW_INITIATED', 'DISPOSAL_DESTRUCTION_RECORDED', 'DISPOSAL_DATA_WIPE_COMPLETED',
    'DISPOSAL_ENVIRONMENTAL_CHECK_COMPLETED', 'DISPOSAL_PICKUP_SCHEDULED',
    'DISPOSAL_TASK_UPDATED', 'DISPOSAL_WORKFLOW_CANCELLED',
    // EAM events
    'WORK_ORDER_CREATED', 'WORK_ORDER_COMPLETED', 'WORK_ORDER_ASSIGNED', 'WORK_ORDER_STATUS_CHANGED',
    'WORK_ORDER_PART_ADDED', 'WORK_ORDER_PART_USED', 'WORK_ORDER_PART_REMOVED',
    'MAINTENANCE_DUE', 'MAINTENANCE_PLAN_CREATED', 'MAINTENANCE_PLAN_UPDATED', 'MAINTENANCE_PLAN_DEACTIVATED',
    'LINEAR_ASSET_CREATED', 'LINEAR_ASSET_UPDATED', 'LINEAR_ASSET_DELETED',
    'SEGMENT_CREATED', 'SEGMENT_UPDATED', 'SEGMENT_DELETED',
    'ASSET_HIERARCHY_LINKED', 'ASSET_HIERARCHY_UNLINKED', 'ASSET_STATUS_PROPAGATED',
    'PARTS_RESERVED', 'PARTS_REPLENISHMENT_NEEDED', 'PARTS_CONSUMED', 'PARTS_RESERVATION_CANCELLED',
    'PART_QUANTITY_ADJUSTED', 'PART_BELOW_REORDER_POINT', 'PART_STOCK_RECEIVED',
    // Contract events
    'CONTRACT_EXPIRING', 'CONTRACT_RENEWED', 'CONTRACT_CREATED', 'CONTRACT_UPDATED',
    'CONTRACT_ASSET_LINKED', 'CONTRACT_ASSET_UNLINKED',
    'CONTRACT_ENTITLEMENT_LINKED', 'CONTRACT_ENTITLEMENT_UNLINKED',
    'PURCHASE_ORDER_CREATED', 'PURCHASE_ORDER_RECEIVED',
    'PURCHASE_ORDER_SUBMITTED', 'PURCHASE_ORDER_APPROVED',
    'PO_REJECTED', 'PO_CANCELLED', 'PO_SENT',
    'PO_LINE_ADDED', 'PO_LINE_REMOVED', 'PO_LINE_UPDATED',
    'APPROVAL_REMINDER_SENT',
    'PROCUREMENT_PROCESSED', 'RESERVATION_RELEASED', 'RESERVATION_FULFILLED',
    // Request events
    'REQUEST_SUBMITTED', 'REQUEST_APPROVED', 'REQUEST_REJECTED', 'REQUEST_FULFILLED', 'REQUEST_CANCELLED',
    'APPROVAL_WORKFLOW_INITIATED', 'APPROVAL_REQUIRED', 'APPROVAL_STEP_COMPLETED', 'APPROVAL_DELEGATED',
    // Lifecycle events
    'RECEIVING_STARTED', 'RECEIVING_PROGRESS', 'RECEIVING_COMPLETED', 'RECEIVING_CANCELLED',
    'INSPECTION_REQUIRED', 'INSPECTION_PASSED', 'INSPECTION_FAILED', 'INSPECTION_ROUTED_TO_RETURN',
    'RETIREMENT_WORKFLOW_INITIATED', 'RETIREMENT_DATA_WIPE_COMPLETED',
    'RETIREMENT_TASK_UPDATED', 'RETIREMENT_WORKFLOW_CANCELLED',
    'CMDB_RELATIONSHIP_CREATED', 'DISCOVERY_CORRELATED', 'DISCOVERY_AUTO_CORRELATED', 'DEPLOYMENT_CANCELLED',
    // Integration events
    'DISCOVERY_DATA_RECEIVED', 'DISCOVERY_DATA_INGESTED', 'ERP_DATA_SYNCED', 'ASN_RECEIVED', 'INTEGRATION_ERROR',
    // Notification events
    'NOTIFICATION_SENT', 'NOTIFICATION_READ', 'NOTIFICATIONS_ALL_READ', 'NOTIFICATION_PREFERENCES_UPDATED',
    // Admin events
    'BUILDING_CREATED', 'BUILDING_UPDATED', 'BUILDING_DEACTIVATED',
    'FLOOR_CREATED', 'FLOOR_UPDATED', 'FLOOR_DEACTIVATED',
    'ROOM_CREATED', 'ROOM_UPDATED', 'ROOM_DEACTIVATED',
    'RACK_CREATED', 'RACK_UPDATED', 'RACK_DEACTIVATED',
    'BIN_LOCATION_CREATED', 'BIN_LOCATION_UPDATED',
    'STOCKROOM_CREATED', 'STOCKROOM_UPDATED', 'STOCKROOM_DEACTIVATED',
    'DEPARTMENT_CREATED', 'DEPARTMENT_UPDATED', 'DEPARTMENT_DEACTIVATED',
    'COST_CENTER_CREATED', 'COST_CENTER_UPDATED',
    'VENDOR_CREATED', 'VENDOR_UPDATED', 'VENDOR_RATING_CHANGED', 'VENDOR_DEACTIVATED',
    'MANUFACTURER_CREATED', 'MANUFACTURER_UPDATED',
    'MODEL_CREATED', 'MODEL_UPDATED', 'MODEL_END_OF_LIFE',
    // User Admin events
    'USER_UPDATED', 'USER_DEACTIVATED', 'USER_REACTIVATED',
    'USER_ROLE_ASSIGNED', 'USER_ROLE_REMOVED',
    // Report events
    'REPORT_GENERATED', 'REPORT_EXPORTED',
];
/**
 * Map event types to their categories
 */
exports.EVENT_CATEGORIES = {
    // Asset events
    ASSET_CREATED: 'ASSET', ASSET_UPDATED: 'ASSET', ASSET_DELETED: 'ASSET', ASSET_STATE_CHANGED: 'ASSET',
    ASSET_ASSIGNED: 'ASSET', ASSET_DEPLOYED: 'ASSET', ASSET_RETIRED: 'ASSET', ASSET_REASSIGNED: 'ASSET',
    // SAM events
    RECONCILIATION_COMPLETED: 'SAM', RECONCILIATION_RUN_COMPLETED: 'SAM',
    RECLAMATION_INITIATED: 'SAM', RECLAMATION_STATUS_CHANGED: 'SAM', RECLAMATION_CANDIDATE_IDENTIFIED: 'SAM',
    RECLAMATION_IDENTIFICATION_COMPLETED: 'SAM', RECLAMATION_WORKFLOW_INITIATED: 'SAM',
    RECLAMATION_USER_NOTIFICATION: 'SAM', RECLAMATION_MANAGER_NOTIFICATION: 'SAM',
    RECLAMATION_APPROVED: 'SAM', RECLAMATION_REJECTED: 'SAM', RECLAMATION_COMPLETED: 'SAM', RECLAMATION_CANCELLED: 'SAM',
    SHADOW_IT_DETECTED: 'SAM', SHADOW_IT_ALERT_CREATED: 'SAM', SHADOW_IT_ANALYSIS_COMPLETED: 'SAM',
    SHADOW_IT_STATUS_CHANGED: 'SAM', SHADOW_IT_ALERT_ACKNOWLEDGED: 'SAM', SHADOW_IT_ALERT_RESOLVED: 'SAM', SHADOW_IT_ALERT_IGNORED: 'SAM',
    SAAS_SUBSCRIPTION_CREATED: 'SAM', SAAS_SUBSCRIPTION_UPDATED: 'SAM', SAAS_USAGE_SYNCED: 'SAM',
    SAAS_OPTIMIZATION_OPPORTUNITIES_FOUND: 'SAM', SAAS_RENEWAL_NOTIFICATION_CREATED: 'SAM',
    SAAS_RENEWAL_NOTIFICATION_SENT: 'SAM', SAAS_RENEWAL_NOTIFICATION_ACKNOWLEDGED: 'SAM', SAAS_SUBSCRIPTION_DELETED: 'SAM',
    PUBLISHER_CALCULATION_COMPLETED: 'SAM', COMPLIANCE_REPORT_GENERATED: 'SAM', COMPLIANCE_REPORT_EXPORTED: 'SAM',
    // HAM events
    TRANSFER_ORDER_CREATED: 'HAM', TRANSFER_ORDER_COMPLETED: 'HAM', TRANSFER_ORDER_APPROVED: 'HAM',
    TRANSFER_ORDER_REJECTED: 'HAM', TRANSFER_ORDER_SHIPPED: 'HAM', TRANSFER_ORDER_CANCELLED: 'HAM', TRANSFER_LINE_RECEIVED: 'HAM',
    STOCK_LEVEL_ALERT: 'HAM', INVENTORY_CREATED: 'HAM', INVENTORY_UPDATED: 'HAM', INVENTORY_ADJUSTED: 'HAM',
    INVENTORY_RESERVED: 'HAM', INVENTORY_RESERVATION_RELEASED: 'HAM', REPLENISHMENT_ALERT: 'HAM',
    LOANER_CHECKOUT: 'HAM', LOANER_RETURNED: 'HAM', LOANER_OVERDUE: 'HAM',
    LOANER_CHECKED_OUT: 'HAM', LOANER_OVERDUE_NOTIFICATION: 'HAM', LOANER_DUE_DATE_EXTENDED: 'HAM',
    AUDIT_COMPLETED: 'HAM', AUDIT_SCAN_RECORDED: 'HAM', DISPOSAL_COMPLETED: 'HAM',
    DISPOSAL_WORKFLOW_INITIATED: 'HAM', DISPOSAL_DESTRUCTION_RECORDED: 'HAM', DISPOSAL_DATA_WIPE_COMPLETED: 'HAM',
    DISPOSAL_ENVIRONMENTAL_CHECK_COMPLETED: 'HAM', DISPOSAL_PICKUP_SCHEDULED: 'HAM',
    DISPOSAL_TASK_UPDATED: 'HAM', DISPOSAL_WORKFLOW_CANCELLED: 'HAM',
    // EAM events
    WORK_ORDER_CREATED: 'EAM', WORK_ORDER_COMPLETED: 'EAM', WORK_ORDER_ASSIGNED: 'EAM', WORK_ORDER_STATUS_CHANGED: 'EAM',
    WORK_ORDER_PART_ADDED: 'EAM', WORK_ORDER_PART_USED: 'EAM', WORK_ORDER_PART_REMOVED: 'EAM',
    MAINTENANCE_DUE: 'EAM', MAINTENANCE_PLAN_CREATED: 'EAM', MAINTENANCE_PLAN_UPDATED: 'EAM', MAINTENANCE_PLAN_DEACTIVATED: 'EAM',
    LINEAR_ASSET_CREATED: 'EAM', LINEAR_ASSET_UPDATED: 'EAM', LINEAR_ASSET_DELETED: 'EAM',
    SEGMENT_CREATED: 'EAM', SEGMENT_UPDATED: 'EAM', SEGMENT_DELETED: 'EAM',
    ASSET_HIERARCHY_LINKED: 'EAM', ASSET_HIERARCHY_UNLINKED: 'EAM', ASSET_STATUS_PROPAGATED: 'EAM',
    PARTS_RESERVED: 'EAM', PARTS_REPLENISHMENT_NEEDED: 'EAM', PARTS_CONSUMED: 'EAM', PARTS_RESERVATION_CANCELLED: 'EAM',
    PART_QUANTITY_ADJUSTED: 'EAM', PART_BELOW_REORDER_POINT: 'EAM', PART_STOCK_RECEIVED: 'EAM',
    // Contract events
    CONTRACT_EXPIRING: 'CONTRACT', CONTRACT_RENEWED: 'CONTRACT', CONTRACT_CREATED: 'CONTRACT', CONTRACT_UPDATED: 'CONTRACT',
    CONTRACT_ASSET_LINKED: 'CONTRACT', CONTRACT_ASSET_UNLINKED: 'CONTRACT',
    CONTRACT_ENTITLEMENT_LINKED: 'CONTRACT', CONTRACT_ENTITLEMENT_UNLINKED: 'CONTRACT',
    PURCHASE_ORDER_CREATED: 'CONTRACT', PURCHASE_ORDER_RECEIVED: 'CONTRACT',
    PURCHASE_ORDER_SUBMITTED: 'CONTRACT', PURCHASE_ORDER_APPROVED: 'CONTRACT',
    PO_REJECTED: 'PROCUREMENT', PO_CANCELLED: 'PROCUREMENT', PO_SENT: 'PROCUREMENT',
    PO_LINE_ADDED: 'PROCUREMENT', PO_LINE_REMOVED: 'PROCUREMENT', PO_LINE_UPDATED: 'PROCUREMENT',
    APPROVAL_REMINDER_SENT: 'PROCUREMENT',
    PROCUREMENT_PROCESSED: 'CONTRACT', RESERVATION_RELEASED: 'CONTRACT', RESERVATION_FULFILLED: 'CONTRACT',
    // Request events
    REQUEST_SUBMITTED: 'REQUEST', REQUEST_APPROVED: 'REQUEST', REQUEST_REJECTED: 'REQUEST', REQUEST_FULFILLED: 'REQUEST', REQUEST_CANCELLED: 'REQUEST',
    APPROVAL_WORKFLOW_INITIATED: 'REQUEST', APPROVAL_REQUIRED: 'REQUEST', APPROVAL_STEP_COMPLETED: 'REQUEST', APPROVAL_DELEGATED: 'REQUEST',
    // Lifecycle events
    RECEIVING_STARTED: 'LIFECYCLE', RECEIVING_PROGRESS: 'LIFECYCLE', RECEIVING_COMPLETED: 'LIFECYCLE', RECEIVING_CANCELLED: 'LIFECYCLE',
    INSPECTION_REQUIRED: 'LIFECYCLE', INSPECTION_PASSED: 'LIFECYCLE', INSPECTION_FAILED: 'LIFECYCLE', INSPECTION_ROUTED_TO_RETURN: 'LIFECYCLE',
    RETIREMENT_WORKFLOW_INITIATED: 'LIFECYCLE', RETIREMENT_DATA_WIPE_COMPLETED: 'LIFECYCLE',
    RETIREMENT_TASK_UPDATED: 'LIFECYCLE', RETIREMENT_WORKFLOW_CANCELLED: 'LIFECYCLE',
    CMDB_RELATIONSHIP_CREATED: 'LIFECYCLE', DISCOVERY_CORRELATED: 'LIFECYCLE', DISCOVERY_AUTO_CORRELATED: 'LIFECYCLE', DEPLOYMENT_CANCELLED: 'LIFECYCLE',
    // Integration events
    DISCOVERY_DATA_RECEIVED: 'INTEGRATION', DISCOVERY_DATA_INGESTED: 'INTEGRATION', ERP_DATA_SYNCED: 'INTEGRATION', ASN_RECEIVED: 'INTEGRATION', INTEGRATION_ERROR: 'INTEGRATION',
    // Notification events
    NOTIFICATION_SENT: 'ADMIN', NOTIFICATION_READ: 'ADMIN', NOTIFICATIONS_ALL_READ: 'ADMIN', NOTIFICATION_PREFERENCES_UPDATED: 'ADMIN',
    // Admin events
    BUILDING_CREATED: 'ADMIN', BUILDING_UPDATED: 'ADMIN', BUILDING_DEACTIVATED: 'ADMIN',
    FLOOR_CREATED: 'ADMIN', FLOOR_UPDATED: 'ADMIN', FLOOR_DEACTIVATED: 'ADMIN',
    ROOM_CREATED: 'ADMIN', ROOM_UPDATED: 'ADMIN', ROOM_DEACTIVATED: 'ADMIN',
    RACK_CREATED: 'ADMIN', RACK_UPDATED: 'ADMIN', RACK_DEACTIVATED: 'ADMIN',
    BIN_LOCATION_CREATED: 'ADMIN', BIN_LOCATION_UPDATED: 'ADMIN',
    STOCKROOM_CREATED: 'ADMIN', STOCKROOM_UPDATED: 'ADMIN', STOCKROOM_DEACTIVATED: 'ADMIN',
    DEPARTMENT_CREATED: 'ADMIN', DEPARTMENT_UPDATED: 'ADMIN', DEPARTMENT_DEACTIVATED: 'ADMIN',
    COST_CENTER_CREATED: 'ADMIN', COST_CENTER_UPDATED: 'ADMIN',
    VENDOR_CREATED: 'ADMIN', VENDOR_UPDATED: 'ADMIN', VENDOR_RATING_CHANGED: 'ADMIN', VENDOR_DEACTIVATED: 'ADMIN',
    MANUFACTURER_CREATED: 'ADMIN', MANUFACTURER_UPDATED: 'ADMIN',
    MODEL_CREATED: 'ADMIN', MODEL_UPDATED: 'ADMIN', MODEL_END_OF_LIFE: 'ADMIN',
    // User Admin events
    USER_UPDATED: 'ADMIN', USER_DEACTIVATED: 'ADMIN', USER_REACTIVATED: 'ADMIN',
    USER_ROLE_ASSIGNED: 'ADMIN', USER_ROLE_REMOVED: 'ADMIN',
    // Report events
    REPORT_GENERATED: 'REPORT', REPORT_EXPORTED: 'REPORT',
};
/**
 * Get the category for an event type
 */
function getEventCategory(eventType) {
    return exports.EVENT_CATEGORIES[eventType];
}
/**
 * Check if an event type is valid
 */
function isValidEventType(eventType) {
    return exports.ALL_EVENT_TYPES.includes(eventType);
}
/**
 * Create a new event with common fields populated
 */
function createEvent(eventType, payload, source, correlationId) {
    return {
        eventId: crypto.randomUUID(),
        eventType,
        timestamp: new Date().toISOString(),
        version: '1.0',
        source,
        correlationId,
        payload,
    };
}
/**
 * Extract metadata from an event for SNS message attributes
 */
function extractEventMetadata(event) {
    const metadata = {
        eventType: event.eventType,
        source: event.source,
        eventId: event.eventId,
    };
    if ('assetType' in event.payload) {
        return { ...metadata, assetType: event.payload.assetType };
    }
    return metadata;
}
//# sourceMappingURL=events.js.map
