/**
 * Mock data for the License Workbench
 * Used for development and testing
 * Implements Requirement 12.5: License Workbench
 * Implements Requirement 4.10: Display compliance positions, audit risks, and optimization opportunities
 */

import type {
  CompliancePosition,
  AuditRisk,
  ReclamationOpportunity,
  LicenseWorkbenchSummary,
} from '../../types/license';

/**
 * Mock compliance positions
 */
export const mockCompliancePositions: CompliancePosition[] = [
  {
    productId: 'product-001',
    publisher: 'Microsoft',
    productName: 'Microsoft 365 E3',
    version: '2024',
    productCategory: 'Productivity Suite',
    licenseMetricType: 'SUBSCRIPTION',
    entitlementsOwned: 500,
    installationsFound: 485,
    compliancePosition: 'COMPLIANT',
    overUnderCount: 15,
    lastReconciledDate: '2025-01-26T08:00:00Z',
    unitCost: 432,
    totalEntitlementValue: 216000,
    potentialExposure: 0,
  },
  {
    productId: 'product-002',
    publisher: 'Microsoft',
    productName: 'SQL Server Enterprise',
    version: '2022',
    edition: 'Enterprise',
    productCategory: 'Database',
    licenseMetricType: 'PER_CORE',
    entitlementsOwned: 48,
    installationsFound: 64,
    compliancePosition: 'UNDER_LICENSED',
    overUnderCount: -16,
    lastReconciledDate: '2025-01-25T14:30:00Z',
    unitCost: 15123,
    totalEntitlementValue: 725904,
    potentialExposure: 241968,
  },
  {
    productId: 'product-003',
    publisher: 'Adobe',
    productName: 'Adobe Creative Cloud',
    version: '2024',
    edition: 'All Apps',
    productCategory: 'Creative Suite',
    licenseMetricType: 'SUBSCRIPTION',
    entitlementsOwned: 150,
    installationsFound: 142,
    compliancePosition: 'COMPLIANT',
    overUnderCount: 8,
    lastReconciledDate: '2025-01-26T06:00:00Z',
    unitCost: 660,
    totalEntitlementValue: 99000,
    potentialExposure: 0,
  },
  {
    productId: 'product-004',
    publisher: 'Oracle',
    productName: 'Oracle Database Enterprise',
    version: '19c',
    edition: 'Enterprise',
    productCategory: 'Database',
    licenseMetricType: 'PER_PROCESSOR',
    entitlementsOwned: 8,
    installationsFound: 12,
    compliancePosition: 'UNDER_LICENSED',
    overUnderCount: -4,
    lastReconciledDate: '2025-01-24T11:00:00Z',
    unitCost: 47500,
    totalEntitlementValue: 380000,
    potentialExposure: 190000,
  },
  {
    productId: 'product-005',
    publisher: 'Salesforce',
    productName: 'Salesforce Sales Cloud',
    version: 'Enterprise',
    productCategory: 'CRM',
    licenseMetricType: 'PER_USER',
    entitlementsOwned: 200,
    installationsFound: 165,
    compliancePosition: 'OVER_LICENSED',
    overUnderCount: 35,
    lastReconciledDate: '2025-01-26T09:15:00Z',
    unitCost: 1800,
    totalEntitlementValue: 360000,
    potentialExposure: 0,
  },
  {
    productId: 'product-006',
    publisher: 'Autodesk',
    productName: 'AutoCAD',
    version: '2024',
    productCategory: 'CAD Software',
    licenseMetricType: 'SUBSCRIPTION',
    entitlementsOwned: 50,
    installationsFound: 48,
    compliancePosition: 'COMPLIANT',
    overUnderCount: 2,
    lastReconciledDate: '2025-01-25T16:45:00Z',
    unitCost: 1865,
    totalEntitlementValue: 93250,
    potentialExposure: 0,
  },
  {
    productId: 'product-007',
    publisher: 'VMware',
    productName: 'vSphere Enterprise Plus',
    version: '8.0',
    productCategory: 'Virtualization',
    licenseMetricType: 'PER_PROCESSOR',
    entitlementsOwned: 24,
    installationsFound: 28,
    compliancePosition: 'UNDER_LICENSED',
    overUnderCount: -4,
    lastReconciledDate: '2025-01-23T10:00:00Z',
    unitCost: 4595,
    totalEntitlementValue: 110280,
    potentialExposure: 18380,
  },
  {
    productId: 'product-008',
    publisher: 'Microsoft',
    productName: 'Windows Server Datacenter',
    version: '2022',
    edition: 'Datacenter',
    productCategory: 'Operating System',
    licenseMetricType: 'PER_CORE',
    entitlementsOwned: 128,
    installationsFound: 112,
    compliancePosition: 'OVER_LICENSED',
    overUnderCount: 16,
    lastReconciledDate: '2025-01-26T07:30:00Z',
    unitCost: 6155,
    totalEntitlementValue: 787840,
    potentialExposure: 0,
  },
];

/**
 * Mock audit risks
 */
export const mockAuditRisks: AuditRisk[] = [
  {
    riskId: 'risk-001',
    productId: 'product-002',
    publisher: 'Microsoft',
    productName: 'SQL Server Enterprise',
    riskLevel: 'critical',
    riskType: 'Under-Licensing',
    description: 'SQL Server Enterprise is under-licensed by 16 cores. Microsoft audits frequently target SQL Server deployments.',
    underLicensedCount: 16,
    estimatedExposure: 241968,
    recommendedAction: 'Purchase additional core licenses or consolidate workloads to reduce core count.',
    lastAssessedDate: '2025-01-25T14:30:00Z',
  },
  {
    riskId: 'risk-002',
    productId: 'product-004',
    publisher: 'Oracle',
    productName: 'Oracle Database Enterprise',
    riskLevel: 'critical',
    riskType: 'Under-Licensing',
    description: 'Oracle Database is under-licensed by 4 processors. Oracle License Management Services (LMS) audits carry significant financial risk.',
    underLicensedCount: 4,
    estimatedExposure: 190000,
    recommendedAction: 'Engage Oracle licensing specialist. Consider migrating to Standard Edition or cloud alternatives.',
    lastAssessedDate: '2025-01-24T11:00:00Z',
  },
  {
    riskId: 'risk-003',
    productId: 'product-007',
    publisher: 'VMware',
    productName: 'vSphere Enterprise Plus',
    riskLevel: 'high',
    riskType: 'Under-Licensing',
    description: 'VMware vSphere is under-licensed by 4 processors. Broadcom has increased audit activity post-acquisition.',
    underLicensedCount: 4,
    estimatedExposure: 18380,
    recommendedAction: 'Purchase additional processor licenses or evaluate subscription conversion.',
    lastAssessedDate: '2025-01-23T10:00:00Z',
  },
  {
    riskId: 'risk-004',
    productId: 'product-009',
    publisher: 'SAP',
    productName: 'SAP S/4HANA',
    riskLevel: 'medium',
    riskType: 'Indirect Access',
    description: 'Potential indirect access exposure from third-party integrations accessing SAP data.',
    underLicensedCount: 0,
    estimatedExposure: 75000,
    recommendedAction: 'Review all system integrations and document data flows. Consider Digital Access licensing.',
    lastAssessedDate: '2025-01-22T09:00:00Z',
  },
  {
    riskId: 'risk-005',
    productId: 'product-010',
    publisher: 'IBM',
    productName: 'IBM MQ',
    riskLevel: 'low',
    riskType: 'Version Compliance',
    description: 'Running older version without active support. May impact compliance during audit.',
    underLicensedCount: 0,
    estimatedExposure: 12000,
    recommendedAction: 'Plan upgrade to supported version or renew support agreement.',
    lastAssessedDate: '2025-01-20T15:00:00Z',
  },
];

/**
 * Mock reclamation opportunities
 */
export const mockReclamationOpportunities: ReclamationOpportunity[] = [
  {
    opportunityId: 'reclaim-001',
    installationId: 'install-001',
    productId: 'product-003',
    publisher: 'Adobe',
    productName: 'Adobe Creative Cloud',
    assignedTo: 'John Smith',
    assignedToEmail: 'john.smith@company.com',
    deviceName: 'LAPTOP-JS001',
    lastUsedDate: '2024-10-15T10:30:00Z',
    daysSinceLastUse: 103,
    reclamationStatus: 'IDENTIFIED',
    estimatedSavings: 660,
    reclamationRuleName: '90 Day Unused Software',
  },
  {
    opportunityId: 'reclaim-002',
    installationId: 'install-002',
    productId: 'product-003',
    publisher: 'Adobe',
    productName: 'Adobe Creative Cloud',
    assignedTo: 'Sarah Johnson',
    assignedToEmail: 'sarah.johnson@company.com',
    deviceName: 'DESKTOP-SJ002',
    lastUsedDate: '2024-09-20T14:00:00Z',
    daysSinceLastUse: 128,
    reclamationStatus: 'PENDING_APPROVAL',
    estimatedSavings: 660,
    reclamationRuleName: '90 Day Unused Software',
  },
  {
    opportunityId: 'reclaim-003',
    installationId: 'install-003',
    productId: 'product-005',
    publisher: 'Salesforce',
    productName: 'Salesforce Sales Cloud',
    assignedTo: 'Mike Chen',
    assignedToEmail: 'mike.chen@company.com',
    deviceName: 'N/A (SaaS)',
    lastUsedDate: '2024-11-01T09:15:00Z',
    daysSinceLastUse: 86,
    reclamationStatus: 'APPROVED',
    estimatedSavings: 1800,
    reclamationRuleName: '60 Day Unused SaaS',
  },
  {
    opportunityId: 'reclaim-004',
    installationId: 'install-004',
    productId: 'product-006',
    publisher: 'Autodesk',
    productName: 'AutoCAD',
    assignedTo: 'Emily Davis',
    assignedToEmail: 'emily.davis@company.com',
    deviceName: 'WORKSTATION-ED001',
    lastUsedDate: '2024-08-10T11:00:00Z',
    daysSinceLastUse: 169,
    reclamationStatus: 'IN_PROGRESS',
    estimatedSavings: 1865,
    reclamationRuleName: '90 Day Unused Software',
  },
  {
    opportunityId: 'reclaim-005',
    installationId: 'install-005',
    productId: 'product-001',
    publisher: 'Microsoft',
    productName: 'Microsoft 365 E3',
    assignedTo: 'Alex Turner',
    assignedToEmail: 'alex.turner@company.com',
    deviceName: 'N/A (SaaS)',
    lastUsedDate: '2024-12-01T08:45:00Z',
    daysSinceLastUse: 56,
    reclamationStatus: 'IDENTIFIED',
    estimatedSavings: 432,
    reclamationRuleName: '45 Day Unused SaaS',
  },
  {
    opportunityId: 'reclaim-006',
    installationId: 'install-006',
    productId: 'product-005',
    publisher: 'Salesforce',
    productName: 'Salesforce Sales Cloud',
    assignedTo: 'Lisa Wang',
    assignedToEmail: 'lisa.wang@company.com',
    deviceName: 'N/A (SaaS)',
    lastUsedDate: '2024-10-25T16:30:00Z',
    daysSinceLastUse: 93,
    reclamationStatus: 'COMPLETED',
    estimatedSavings: 1800,
    reclamationRuleName: '60 Day Unused SaaS',
  },
];

/**
 * Complete mock license workbench summary
 */
export const mockLicenseWorkbenchSummary: LicenseWorkbenchSummary = {
  totalSoftwareTitles: mockCompliancePositions.length,
  compliantCount: mockCompliancePositions.filter(p => p.compliancePosition === 'COMPLIANT').length,
  overLicensedCount: mockCompliancePositions.filter(p => p.compliancePosition === 'OVER_LICENSED').length,
  underLicensedCount: mockCompliancePositions.filter(p => p.compliancePosition === 'UNDER_LICENSED').length,
  totalEntitlementValue: mockCompliancePositions.reduce((sum, p) => sum + p.totalEntitlementValue, 0),
  totalPotentialExposure: mockCompliancePositions.reduce((sum, p) => sum + p.potentialExposure, 0),
  totalReclamationSavings: mockReclamationOpportunities
    .filter(r => r.reclamationStatus !== 'COMPLETED' && r.reclamationStatus !== 'CANCELLED')
    .reduce((sum, r) => sum + r.estimatedSavings, 0),
  criticalRisksCount: mockAuditRisks.filter(r => r.riskLevel === 'critical').length,
  highRisksCount: mockAuditRisks.filter(r => r.riskLevel === 'high').length,
  reclamationOpportunitiesCount: mockReclamationOpportunities.filter(
    r => r.reclamationStatus !== 'COMPLETED' && r.reclamationStatus !== 'CANCELLED'
  ).length,
  compliancePositions: mockCompliancePositions,
  auditRisks: mockAuditRisks,
  reclamationOpportunities: mockReclamationOpportunities,
};

/**
 * Helper to simulate API loading delay
 */
export function simulateApiDelay<T>(data: T, delayMs = 1000): Promise<T> {
  return new Promise((resolve) => {
    setTimeout(() => resolve(data), delayMs);
  });
}
